version: "3.8"
services:
    mongodb:
        container_name: mongodb
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${DB_NAME}
        ports:
            - ${DB_PORT}:27017
        volumes:
            - mongodb_data_container:/data/db
    client-server:
        container_name: client-server
        build: ./client-server/svelte
        ports: 
            - "5000:5000"
    node:
        container_name: node-api
        depends_on: 
            - mongodb
        build:
            context: .
            dockerfile: 
                ./server/Dockerfile
        environment:
            - DB_GATEWAY=${DB_GATEWAY}
            - DB_URI=${DB_URI}
            - DB_PROTOCOL=${DB_PROTOCOL}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - PORT=${PORT}
            - AUTO_PORT=${AUTO_PORT}
            - ACTIONS_TO_LOG=${ACTIONS_TO_LOG}
            - ERRORS_TO_LOG=${ERRORS_TO_LOG}
            - TRACEBACKS_TO_LOG=${TRACEBACKS_TO_LOG}
        ports:
            - ${PORT}:3000
            - "9229:9229"
        command:
            - node
            - "--inspect=0.0.0.0"
            - "./index.js"
        links:
            - mongodb
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
            - "443:443"
volumes:
    mongodb_data_container:        