version: "3.8"
services:
    mongodb:
        container_name: mongodb
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${DB_NAME}
        ports:
            - ${DB_PORT}:27017
        volumes:
            - mongodb_data_container:/data/db
    node:
        container_name: node-api
        depends_on: 
            - mongodb
        build:
            context: .
            dockerfile: 
                ./server/Dockerfile
        ports:
            - ${PORT}:3000
            - "9229:9229"
        command:
            - node
            - "--inspect=0.0.0.0"
            - "./index.js"
        links:
            - mongodb
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
            - "443:443"
volumes:
    mongodb_data_container:        