version: "3.8"
services:
    mongodb-server:
        container_name: mongodb-server
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${DB_NAME}
            DB_AUTH_USER: ${DB_AUTH_USER}
            DB_AUTH_PWD: ${DB_AUTH_PWD}
            DB_USER: ${DB_USER}
            DB_PWD: ${DB_PWD}
        ports:
            - ${DB_PORT}:27017
        volumes:
            - mongodb_data_container:/data/db
            # - ./.docker/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    client-server:
        container_name: client-server
        build: ./client-server/svelte
    auth-server:
        container_name: auth-server
        depends_on: 
            - mongodb-server
        build: ./auth-server
        volumes:
            - ./packages:/usr/src/packages
        environment:
            - DB_GATEWAY=${DB_GATEWAY}
            - DB_URI=${DB_URI}
            - DB_PROTOCOL=${DB_PROTOCOL}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - PORT=${PORT}
            - AUTO_PORT=${AUTO_PORT}
            - ACTIONS_TO_LOG=${ACTIONS_TO_LOG}
            - ERRORS_TO_LOG=${ERRORS_TO_LOG}
            - TRACEBACKS_TO_LOG=${TRACEBACKS_TO_LOG}
        links:
            - mongodb-server:mongodb
    resource-server:
        container_name: resourece-server
        depends_on: 
            - mongodb-server
        build: ./resource-server
        environment:
            - DB_GATEWAY=${DB_GATEWAY}
            - DB_URI=${DB_URI}
            - DB_PROTOCOL=${DB_PROTOCOL}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - PORT=${PORT}
            - AUTO_PORT=${AUTO_PORT}
            - ACTIONS_TO_LOG=${ACTIONS_TO_LOG}
            - ERRORS_TO_LOG=${ERRORS_TO_LOG}
            - TRACEBACKS_TO_LOG=${TRACEBACKS_TO_LOG}
        ports:
            - "9229:9229"
        command:
            - node
            - ${INSPECT_FLAG}
            - "./index.js"
        links:
            - mongodb-server:mongodb
    nginx:
        restart: always
        build:
            context: ./nginx-server
        links:
            - auth-server:auth
            - resource-server:resource
            - client-server:frontend
        ports:
            - "80:80"
            - "443:443"
volumes:
    mongodb_data_container:
    