version: "3.8"
services:
    mongodb-server:
        container_name: mongodb-server
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PWD}
            MONGO_INITDB_DATABASE: ${DB_NAME}
            DB_AUTH_USER: ${DB_AUTH_USER}
            DB_AUTH_PWD: ${DB_AUTH_PWD}
            DB_USER: ${DB_USER}
            DB_PWD: ${DB_PWD}
        ports:
            - ${DB_PORT}:27017
        volumes:
            - mongodb:/data/db
            - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    client-server:
        container_name: client-server
        build: ./client-server
        # volumes:
        #     - ./client-server/svelte/src:/usr/src/app/svelte/src
    auth-server:
        container_name: auth-server
        depends_on: 
            - mongodb-server
        build: ./auth-server
        volumes:
            - ./packages:/usr/src/packages
        environment:
            - DB_GATEWAY=${DB_GATEWAY}
            - DB_PROTOCOL=${DB_PROTOCOL}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_AUTH_USER}
            - DB_PWD=${DB_AUTH_PWD}
            - PORT=${AUTH_SERVER_PORT}
            - EVENTS_TO_LOG=${AUTH_SERVER_EVENTS}
            - ERRORS_TO_LOG=${AUTH_SERVER_ERRORS}
            - TRACEBACKS_TO_LOG=${AUTH_SERVER_TRACEBACKS}
        command:
            - node
            - ${AUTH_SERVER_FLAGS}
            - "./index.js"
        ports:
            - 9229:9229
        links:
            - mongodb-server:mongodb
    resource-server:
        container_name: resourece-server
        depends_on: 
            - mongodb-server
        build: ./resource-server
        environment:
            - DB_GATEWAY=${DB_GATEWAY}
            - DB_PROTOCOL=${DB_PROTOCOL}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PWD=${DB_PWD}
            - PORT=${RESOURCE_SERVER_PORT}
            - EVENTS_TO_LOG=${RESOURCE_SERVER_EVENTS}
            - ERRORS_TO_LOG=${RESOURCE_SERVER_ERRORS}
            - TRACEBACKS_TO_LOG=${RESOURCE_SERVER_TRACEBACKS}
            - CART_TIMEOUT=${CART_TIMEOUT}
        # ports:
        #     - "9229:9229"
        # command:
        #     - node
        #     - ${RESOURCE_SERVER_FLAGS}
        #     - "./index.js"
        links:
            - mongodb-server:mongodb
        volumes:
            - ./packages:/usr/src/packages
    nginx:
        restart: always
        build:
            context: ./nginx-server
        links:
            - auth-server:auth
            - resource-server:resource
            - client-server:frontend
        ports:
            - "80:80"
            - "443:443"
volumes:
    mongodb:
    